function [Rb,Rm] = RFunc_SR2(in1)
%RFunc_SR2
%    [Rb,Rm] = RFunc_SR2(IN1)

%    This function was generated by the Symbolic Math Toolbox version 9.1.
%    23-Sep-2022 16:56:28

qm1 = in1(7,:);
qm2 = in1(8,:);
Rb = reshape([1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0],[6,6]);
if nargout > 1
    t2 = cos(qm1);
    t3 = cos(qm2);
    t4 = sin(qm1);
    t5 = sin(qm2);
    Rm = reshape([t2,t4,0.0,-t4,t2,0.0,0.0,0.0,1.0,t3,t5,0.0,-t5,t3,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0],[3,9]);
end
