function [Rb,Ra,Rm] = RFunc_SR2(in1)
%RFunc_SR2
%    [Rb,Ra,Rm] = RFunc_SR2(IN1)

%    This function was generated by the Symbolic Math Toolbox version 9.1.
%    06-Oct-2022 16:39:19

p = in1(5,:);
qm1 = in1(7,:);
qm2 = in1(8,:);
r = in1(4,:);
y = in1(6,:);
t2 = cos(p);
t3 = cos(qm1);
t4 = cos(qm2);
t5 = cos(r);
t6 = cos(y);
t7 = sin(p);
t8 = sin(qm1);
t9 = sin(qm2);
t10 = sin(r);
t11 = sin(y);
Rb = reshape([t2.*t6,t2.*t11,-t7,-t5.*t11+t6.*t7.*t10,t5.*t6+t7.*t10.*t11,t2.*t10,t10.*t11+t5.*t6.*t7,-t6.*t10+t5.*t7.*t11,t2.*t5],[3,3]);
if nargout > 1
    Ra = reshape([1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0],[6,6]);
end
if nargout > 2
    Rm = reshape([t3,t8,0.0,-t8,t3,0.0,0.0,0.0,1.0,t4,t9,0.0,-t9,t4,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0],[3,9]);
end
